metaData:
  header:
    - id: name
      caption: 标题
      dataType: string
      showable: true
      searchable: true
      nullable: false
      editable: true
    - id: code
      caption: 标识
      dataType: string
      showable: true
      searchable: true
      nullable: false
      editable: true
    - id: items
      caption: 枚举列表
      dataType: array
      arrays:
        value:
          caption: 枚举值
          dataType: int
        text:
          caption: 枚举文本
          dataType: string
      showable: true
      searchable: false
      nullable: false
      editable: true
  buttonList:
  - {id: Plus, icon: plus, text: 新建}
  - {id: Edit, icon: edit, text: 编辑}
  - {id: Delete, icon: delete, text: 删除}